#!/usr/bin/env bash
# Point each harness's GLOBAL instruction file at this repo, so agents load the vault's rules even
# when opened somewhere else on the machine.
#
# The companion to install-skills.sh: that one deploys skills/, this one deploys the always-on
# instruction bridge. Without it, a harness only sees these rules when opened ON this repo — which is
# the "works on my laptop, not the new one" gap in memory/environment.md.
#
# Usage:
#   _Agents/scripts/install-instructions.sh [--force] [--dry-run]
#
# Options:
#   --force     overwrite an existing file that this script did not write. Off by default, because
#               a hand-written global instruction file is worth more than this stub.
#   --dry-run   print what would be written; touch nothing.
#   -h, --help  show this help
#
# Targets are discovered, not assumed: a stub is written only where the harness's config directory
# already exists. Installing a new harness later just means re-running this.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MARKER="<!-- generated by _Agents/scripts/install-instructions.sh -->"
LEGACY_MARKER="<!-- generated by .agents/scripts/install-instructions.sh -->"

force="no"; dry="no"
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    --force) force="yes"; shift ;;
    --dry-run) dry="yes"; shift ;;
    *) echo "unknown arg: $1 (try --help)" >&2; exit 1 ;;
  esac
done

# dir-that-must-exist : file to write
targets=(
  "$HOME/.claude:$HOME/.claude/CLAUDE.md"
  "$HOME/.codex:$HOME/.codex/AGENTS.md"
  "$HOME/.gemini:$HOME/.gemini/GEMINI.md"
  "$HOME/.cursor:$HOME/.cursor/AGENTS.md"
)

stub() {  # stub <harness-file-name>
  cat <<EOF
# Global agent instructions

$MARKER

**Read \`$REPO_ROOT/AGENTS.md\`.** It is the single source of instructions for
every AI agent working with this user, and it applies to you unchanged — in this repo or any other.

The operating model in one line: **one brain, many disposable agents.** The vault is the memory —
search it for prompt-specific context before acting or asking the user to re-explain anything.
Load skills, machine context, credentials, and topic memory only when the request requires them;
\`$REPO_ROOT/AGENTS.md\` defines that routing.

**If a skill name exists twice, use the unprefixed one.** Skills are authored in the repo above and may
also be installed from a marketplace or shared repo, so the same name can appear as \`foo\` and as
\`some-plugin:foo\`. The unprefixed copy is the source of truth; the prefixed one is a published build
artifact that may be behind. Only reach for \`plugin:skill\` when there is no unprefixed skill of that
name.

## Working style

- Be pragmatic, direct, warm, and collaborative. Optimize for completing the user's actual goal, not
  displaying process.
- Default verbosity is concise: about 3/10. Handle simple requests in a few lines; add depth when
  complexity, risk, or the user's request warrants it.
- Lead with the outcome. Then give the evidence, important changes, caveats, or decisions needed to
  understand it.
- Use plain language first. Include technical detail only when it helps the user evaluate, use, test,
  or safely change the result.
- Use the minimum formatting needed. Avoid ceremonial headings, praise, restating the request, filler,
  repetitive summaries, and unsolicited next steps.
- For ongoing tool work, give brief progress updates and continue until the outcome is achieved or
  genuinely blocked. Do not narrate routine mechanics.
- Make reasonable, reversible assumptions instead of stopping unnecessarily. State assumptions only
  when they materially affect the result.
- Distinguish verified facts from inference. Report what was tested, what passed, and what remains
  unverified.
- Final responses must stand alone: concise outcome, verification, and any meaningful limitation.
EOF
}

wrote=0; skipped=0
for t in "${targets[@]}"; do
  dir="${t%%:*}"; file="${t#*:}"
  [[ -d "$dir" ]] || { echo "skip     $file (no $dir — harness not installed)"; continue; }

  if [[ -s "$file" ]] && ! grep -qF "$MARKER" "$file" 2>/dev/null \
      && ! grep -qF "$LEGACY_MARKER" "$file" 2>/dev/null && [[ "$force" != "yes" ]]; then
    echo "REFUSE   $file (hand-written; re-run with --force to replace)" >&2
    skipped=$((skipped + 1))
    continue
  fi

  if [[ "$dry" == "yes" ]]; then
    echo "would write $file"
  else
    stub > "$file"
    echo "wrote    $file"
  fi
  wrote=$((wrote + 1))
done

echo "done. $wrote written, $skipped left alone."
[[ $skipped -gt 0 ]] && echo "note: a refused file already carries real content — merge the pointer in by hand."
exit 0
